### ISSUE TITLE
adb: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by adiov** [nixu-corp/aet#1]
The script doesn't detect the correct platform (32bit or 64bit) and downloads Android SDK for 64bit. This means it fails on 32-bit systems.

When running the emulator, I get the following error

> bin/run-emulator.sh ~/android-sdk/ android-17-default
> Starting AVD: android-17-default
> Waiting./root/aet/emulator-utilities.sh: line 38: /root/android-sdk/android-sdk-linux/platform-tools/adb: cannot execute binary file: Exec format error

**Comment by doc97** [comment]
Google has dropped support for the 32-bit version of the Android SDK, but you can see if this StackOverflow answer helps you.
http://askubuntu.com/questions/710426/android-sdk-on-ubuntu-32bit
It might be possible to download via your local package manager.
